
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += ../FRUITY3/src/main.cpp

SRC += ../FRUITY3/img/logo.cpp

SRC += ../FRUITY3/snd/051.cpp
SRC += ../FRUITY3/snd/052.cpp
SRC += ../FRUITY3/snd/053.cpp
SRC += ../FRUITY3/snd/054.cpp
SRC += ../FRUITY3/snd/055.cpp
SRC += ../FRUITY3/snd/056.cpp
SRC += ../FRUITY3/snd/057.cpp
SRC += ../FRUITY3/snd/058.cpp
SRC += ../FRUITY3/snd/059.cpp
SRC += ../FRUITY3/snd/060.cpp
SRC += ../FRUITY3/snd/061.cpp
SRC += ../FRUITY3/snd/062.cpp
SRC += ../FRUITY3/snd/063.cpp
SRC += ../FRUITY3/snd/064.cpp
SRC += ../FRUITY3/snd/065.cpp
SRC += ../FRUITY3/snd/066.cpp
SRC += ../FRUITY3/snd/067.cpp
SRC += ../FRUITY3/snd/068.cpp
SRC += ../FRUITY3/snd/069.cpp
SRC += ../FRUITY3/snd/070.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
