// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// vga //
// --- //

#define vga_wrap_target 11
#define vga_wrap 15

#define vga_offset_hsync 0u
#define vga_offset_entry 1u
#define vga_offset_vsync 3u
#define vga_offset_vhsync 6u
#define vga_offset_dark 9u
#define vga_offset_output 13u

static const uint16_t vga_program_instructions[] = {
    0x0840, //  0: jmp    x--, 0          side 1     
    0x683b, //  1: out    x, 27           side 1     
    0x68a5, //  2: out    pc, 5           side 1     
    0x1043, //  3: jmp    x--, 3          side 2     
    0x703b, //  4: out    x, 27           side 2     
    0x70a5, //  5: out    pc, 5           side 2     
    0x1846, //  6: jmp    x--, 6          side 3     
    0x783b, //  7: out    x, 27           side 3     
    0x78a5, //  8: out    pc, 5           side 3     
    0xa003, //  9: mov    pins, null      side 0     
    0x004a, // 10: jmp    x--, 10         side 0     
            //     .wrap_target
    0x603b, // 11: out    x, 27           side 0     
    0x60a5, // 12: out    pc, 5           side 0     
    0x6210, // 13: out    pins, 16        side 0 [2] 
    0x014d, // 14: jmp    x--, 13         side 0 [1] 
    0x6210, // 15: out    pins, 16        side 0 [2] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program vga_program = {
    .instructions = vga_program_instructions,
    .length = 16,
    .origin = -1,
};

static inline pio_sm_config vga_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + vga_wrap_target, offset + vga_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}
#endif

