
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/logo.cpp

SRC += snd/051.cpp
SRC += snd/052.cpp
SRC += snd/053.cpp
SRC += snd/054.cpp
SRC += snd/055.cpp
SRC += snd/056.cpp
SRC += snd/057.cpp
SRC += snd/058.cpp
SRC += snd/059.cpp
SRC += snd/060.cpp
SRC += snd/061.cpp
SRC += snd/062.cpp
SRC += snd/063.cpp
SRC += snd/064.cpp
SRC += snd/065.cpp
SRC += snd/066.cpp
SRC += snd/067.cpp
SRC += snd/068.cpp
SRC += snd/069.cpp
SRC += snd/070.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
