
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/tiles.cpp

SRC += snd/brick.cpp
SRC += snd/gameover.cpp
SRC += snd/levelup.cpp
SRC += snd/line.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
