
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/clouds.cpp
SRC += img/hotair.cpp
SRC += img/blue.cpp
SRC += img/green.cpp
SRC += img/red.cpp
SRC += img/yellow.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
