
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/brush.cpp
SRC += img/colsel.cpp
SRC += img/colsel2.cpp
SRC += img/colsel3.cpp
SRC += img/palette.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
