
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/brush.cpp
SRC += img/colsel.cpp
SRC += img/colsel2.cpp
SRC += img/colsel3.cpp
SRC += img/palette.cpp

# Makefile includes
include ../../../Makefile.inc
