CSRC += ../../../_lib/src/lib_alarm.c
CSRC += ../../../_lib/src/lib_calendar.c
CSRC += ../../../_lib/src/lib_calendar64.c
CSRC += ../../../_lib/src/lib_canvas.c
CSRC += ../../../_lib/src/lib_color.c
CSRC += ../../../_lib/src/lib_config.c
CSRC += ../../../_lib/src/lib_crc.c
CSRC += ../../../_lib/src/lib_decnum.c
CSRC += ../../../_lib/src/lib_draw.c
CSRC += ../../../_lib/src/lib_escpkt.c
CSRC += ../../../_lib/src/lib_event.c
CSRC += ../../../_lib/src/lib_fat.c
CSRC += ../../../_lib/src/lib_list.c
CSRC += ../../../_lib/src/lib_malloc.c
CSRC += ../../../_lib/src/lib_mat2d.c
CSRC += ../../../_lib/src/lib_miniring.c
CSRC += ../../../_lib/src/lib_print.c
CSRC += ../../../_lib/src/lib_pwmsnd.c
CSRC += ../../../_lib/src/lib_rand.c
CSRC += ../../../_lib/src/lib_rect.c
CSRC += ../../../_lib/src/lib_ring.c
CSRC += ../../../_lib/src/lib_ringrx.c
CSRC += ../../../_lib/src/lib_ringtx.c
CSRC += ../../../_lib/src/lib_sd.c
CSRC += ../../../_lib/src/lib_stream.c
CSRC += ../../../_lib/src/lib_text.c
CSRC += ../../../_lib/src/lib_textlist.c
CSRC += ../../../_lib/src/lib_textnum.c
CSRC += ../../../_lib/src/lib_tprint.c
CSRC += ../../../_lib/src/lib_tree.c
CSRC += ../../../_lib/src/lib_video.c

#CSRC += ../../../_lib/3d_src/lib_d3fixed.c
#CSRC += ../../../_lib/3d_src/lib_d3mat.c
#CSRC += ../../../_lib/3d_src/lib_d3obj.c
#CSRC += ../../../_lib/3d_src/lib_d3vect.c
#CSRC += ../../../_lib/3d_src/lib_d3world.c

# C big integers
CSRC += ../../../_lib/bigint/bigint.c
CSRC += ../../../_lib/bigint/bernoulli.c

# C real numbers
CSRC += ../../../_lib/real/real.c

# ASM sdk
ASRC += ../../../_lib/src/vga_blitkey.S

#ASRC += ../../../_lib/3d_src/lib_d3fixed_asm.S
