
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += ../FRUITY2/src/main.cpp

SRC += ../FRUITY2/img/logo.cpp

SRC += ../FRUITY2/snd/031.cpp
SRC += ../FRUITY2/snd/032.cpp
SRC += ../FRUITY2/snd/033.cpp
SRC += ../FRUITY2/snd/034.cpp
SRC += ../FRUITY2/snd/035.cpp
SRC += ../FRUITY2/snd/036.cpp
SRC += ../FRUITY2/snd/037.cpp
SRC += ../FRUITY2/snd/038.cpp
SRC += ../FRUITY2/snd/039.cpp
SRC += ../FRUITY2/snd/040.cpp
SRC += ../FRUITY2/snd/041.cpp
SRC += ../FRUITY2/snd/042.cpp
SRC += ../FRUITY2/snd/043.cpp
SRC += ../FRUITY2/snd/044.cpp
SRC += ../FRUITY2/snd/045.cpp
SRC += ../FRUITY2/snd/046.cpp
SRC += ../FRUITY2/snd/047.cpp
SRC += ../FRUITY2/snd/048.cpp
SRC += ../FRUITY2/snd/049.cpp
SRC += ../FRUITY2/snd/050.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
