
# ASM source files
ASRC += 

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/digits.cpp
SRC += img/girl_with_kitten.cpp
SRC += img/kittens_in_box.cpp
SRC += img/kittens_in_forest.cpp
SRC += img/kittens_on_meadow.cpp
SRC += img/kittens_with_butterflies.cpp
SRC += img/kittens_with_flowers.cpp
SRC += img/kittens_with_snowdrops.cpp
SRC += img/pegasus.cpp
SRC += img/persian_kitten.cpp
SRC += img/phoenix.cpp
SRC += img/sea_dragon.cpp
SRC += img/tiles.cpp
SRC += img/two_persian_kittens.cpp
SRC += img/two_puppy_dogs.cpp

SRC += snd/move.cpp
SRC += snd/bump.cpp
SRC += snd/shuffling.cpp
SRC += snd/fanfare.cpp

# Makefile includes
include ../../../Makefile.inc
