
# ASM source files
ASRC += 

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/levels.cpp
SRC += src/game.cpp

SRC += img/tiles.cpp

SRC += snd/collect.cpp
SRC += snd/crash.cpp
SRC += snd/step.cpp
SRC += snd/success.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
