@echo off
PicoPadImg digits.bmp digits.cpp DigitsImg
PicoPadImg girl_with_kitten.bmp girl_with_kitten.cpp GirlWithKittenImg
PicoPadImg kittens_in_box.bmp kittens_in_box.cpp KittensInBoxImg
PicoPadImg kittens_in_forest.bmp kittens_in_forest.cpp KittensInForestImg
PicoPadImg kittens_on_meadow.bmp kittens_on_meadow.cpp KittensOnMeadowImg
PicoPadImg kittens_with_butterflies.bmp kittens_with_butterflies.cpp KittensWithButterfliesImg
PicoPadImg kittens_with_flowers.bmp kittens_with_flowers.cpp KittensWithFlowersImg
PicoPadImg kittens_with_snowdrops.bmp kittens_with_snowdrops.cpp KittensWithSnowdropsImg
PicoPadImg pegasus.bmp pegasus.cpp PegasusImg
PicoPadImg persian_kitten.bmp persian_kitten.cpp PersianKittenImg
PicoPadImg phoenix.bmp phoenix.cpp PhoenixImg
PicoPadImg sea_dragon.bmp sea_dragon.cpp SeaDraqonImg
PicoPadImg tiles.bmp tiles.cpp TilesImg
PicoPadImg two_persian_kittens.bmp two_persian_kittens.cpp TwoPersianKittensImg
PicoPadImg two_puppy_dogs.bmp two_puppy_dogs.cpp TwoPuppyDogsImg
