
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += img/CobbleStone.cpp 
SRC += img/Fabric.cpp       
SRC += img/Soil.cpp         
SRC += img/Wood.cpp
SRC += src/main.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
