
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += ../FRUITY6/src/main.cpp

SRC += ../FRUITY6/img/logo.cpp

SRC += ../FRUITY6/snd/110.cpp
SRC += ../FRUITY6/snd/111.cpp
SRC += ../FRUITY6/snd/112.cpp
SRC += ../FRUITY6/snd/113.cpp
SRC += ../FRUITY6/snd/114.cpp
SRC += ../FRUITY6/snd/115.cpp
SRC += ../FRUITY6/snd/116.cpp
SRC += ../FRUITY6/snd/117.cpp
SRC += ../FRUITY6/snd/118.cpp
SRC += ../FRUITY6/snd/119.cpp
SRC += ../FRUITY6/snd/120.cpp
SRC += ../FRUITY6/snd/121.cpp
SRC += ../FRUITY6/snd/122.cpp
SRC += ../FRUITY6/snd/123.cpp
SRC += ../FRUITY6/snd/124.cpp
SRC += ../FRUITY6/snd/125.cpp
SRC += ../FRUITY6/snd/126.cpp
SRC += ../FRUITY6/snd/127.cpp
SRC += ../FRUITY6/snd/128.cpp
SRC += ../FRUITY6/snd/129.cpp
SRC += ../FRUITY6/snd/130.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
