
# PicoDVI library
ASRC += ../_libdvi/tmds_encode_asm.S
ASRC += ../_libsprite/sprite_asm.S
ASRC += ../_libsprite/tile_asm.S

CSRC += ../_libdvi/dvi_lib.c
CSRC += ../_libdvi/dvi_serialiser.c
CSRC += ../_libdvi/dvi_timing.c
CSRC += ../_libdvi/tmds_encode.c
CSRC += ../_libsprite/sprite.c
CSRC += ../_libsprite/tile.c

# ASM source files
ASRC += src/tmds_encode_font_2bpp.S

# C source files
CSRC += src/main.c

# C++ source files
SRC +=

# Makefile includes
include ../../../Makefile.inc
