
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/logo.cpp

SRC += snd/071.cpp
SRC += snd/072.cpp
SRC += snd/073.cpp
SRC += snd/074.cpp
SRC += snd/075.cpp
SRC += snd/076.cpp
SRC += snd/077.cpp
SRC += snd/078.cpp
SRC += snd/079.cpp
SRC += snd/080.cpp
SRC += snd/081.cpp
SRC += snd/082.cpp
SRC += snd/083.cpp
SRC += snd/084.cpp
SRC += snd/085.cpp
SRC += snd/086.cpp
SRC += snd/087.cpp
SRC += snd/088.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
