
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/logo.cpp

SRC += snd/001.cpp
SRC += snd/002.cpp
SRC += snd/003.cpp
SRC += snd/004.cpp
SRC += snd/005.cpp
SRC += snd/006.cpp
SRC += snd/007.cpp
SRC += snd/008.cpp
SRC += snd/009.cpp
SRC += snd/010.cpp
SRC += snd/011.cpp
SRC += snd/012.cpp
SRC += snd/013.cpp
SRC += snd/014.cpp
SRC += snd/015.cpp
SRC += snd/016.cpp
SRC += snd/017.cpp
SRC += snd/018.cpp
SRC += snd/019.cpp
SRC += snd/020.cpp
SRC += snd/021.cpp
SRC += snd/022.cpp
SRC += snd/023.cpp
SRC += snd/024.cpp
SRC += snd/025.cpp
SRC += snd/026.cpp
SRC += snd/027.cpp
SRC += snd/028.cpp
SRC += snd/029.cpp
SRC += snd/030.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
