
# ASM source files
ASRC += 

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/tiles.cpp
SRC += snd/move.cpp
SRC += snd/bump.cpp
SRC += snd/shuffling.cpp
SRC += snd/fanfare.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
