
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += src/myrand.cpp
SRC += src/ref.cpp
SRC += src/test.cpp

# Makefile includes
include ../../../Makefile.inc
