@echo off
RaspPicoSnd music1.wav music1.cpp Music1Snd
RaspPicoSnd music2.wav music2.cpp Music2Snd
RaspPicoSnd music3.wav music3.cpp Music3Snd
RaspPicoSnd music4.wav music4.cpp Music4Snd
RaspPicoSnd music5.wav music5.cpp Music5Snd
RaspPicoSnd music6.wav music6.cpp Music6Snd
RaspPicoSnd music7.wav music7.cpp Music7Snd
RaspPicoSnd music8.wav music8.cpp Music8Snd
RaspPicoSnd music9.wav music9.cpp Music9Snd
RaspPicoSnd music10.wav music10.cpp Music10Snd
RaspPicoSnd music11.wav music11.cpp Music11Snd
RaspPicoSnd music12.wav music12.cpp Music12Snd
RaspPicoSnd enemyhit.wav enemyhit.cpp EnemyHitSnd
RaspPicoSnd swing.wav swing.cpp SwingSnd
RaspPicoSnd minigun.wav minigun.cpp MinigunSnd
RaspPicoSnd gun.wav gun.cpp GunSnd
RaspPicoSnd noise.wav noise.cpp NoiseSnd
RaspPicoSnd electricity.wav electricity.cpp ElectricitySnd
RaspPicoSnd glass.wav glass.cpp GlassSnd
RaspPicoSnd flame.wav flame.cpp FlameSnd
RaspPicoSnd screaming.wav screaming.cpp ScreamingSnd
RaspPicoSnd lasershot.wav lasershot.cpp LaserSnd
RaspPicoSnd phasershot.wav phasershot.cpp PhaserSnd
RaspPicoSnd rocketshot.wav rocketshot.cpp RocketSnd
RaspPicoSnd throw.wav throw.cpp ThrowSnd
RaspPicoSnd blackhole.wav blackhole.cpp BlackholeSnd
RaspPicoSnd blackhole2.wav blackhole2.cpp Blackhole2Snd
RaspPicoSnd fail.wav fail.cpp FailSnd
RaspPicoSnd zing.wav zing.cpp ZingSnd
RaspPicoSnd bigbonus.wav bigbonus.cpp BigbonusSnd
