
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += ../FRUITY1/src/main.cpp

SRC += ../FRUITY1/img/logo.cpp

SRC += ../FRUITY1/snd/001.cpp
SRC += ../FRUITY1/snd/002.cpp
SRC += ../FRUITY1/snd/003.cpp
SRC += ../FRUITY1/snd/004.cpp
SRC += ../FRUITY1/snd/005.cpp
SRC += ../FRUITY1/snd/006.cpp
SRC += ../FRUITY1/snd/007.cpp
SRC += ../FRUITY1/snd/008.cpp
SRC += ../FRUITY1/snd/009.cpp
SRC += ../FRUITY1/snd/010.cpp
SRC += ../FRUITY1/snd/011.cpp
SRC += ../FRUITY1/snd/012.cpp
SRC += ../FRUITY1/snd/013.cpp
SRC += ../FRUITY1/snd/014.cpp
SRC += ../FRUITY1/snd/015.cpp
SRC += ../FRUITY1/snd/016.cpp
SRC += ../FRUITY1/snd/017.cpp
SRC += ../FRUITY1/snd/018.cpp
SRC += ../FRUITY1/snd/019.cpp
SRC += ../FRUITY1/snd/020.cpp
SRC += ../FRUITY1/snd/021.cpp
SRC += ../FRUITY1/snd/022.cpp
SRC += ../FRUITY1/snd/023.cpp
SRC += ../FRUITY1/snd/024.cpp
SRC += ../FRUITY1/snd/025.cpp
SRC += ../FRUITY1/snd/026.cpp
SRC += ../FRUITY1/snd/027.cpp
SRC += ../FRUITY1/snd/028.cpp
SRC += ../FRUITY1/snd/029.cpp
SRC += ../FRUITY1/snd/030.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
