
# C++ source files
SRC += src/main.cpp

SRC += img/DispHSTX_logo.cpp
SRC += img/Img532x400_16b.cpp
SRC += img/pattern.cpp
SRC += img/Img1b.cpp
SRC += img/Img2b.cpp
SRC += img/Img3b.cpp
SRC += img/Img4b.cpp
SRC += img/Img6b.cpp
SRC += img/Img8b.cpp
SRC += img/Img12b.cpp
SRC += img/Img15b.cpp
SRC += img/Img16b.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
