// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// grabber //
// ------- //

#define grabber_wrap_target 2
#define grabber_wrap 29

#define grabber_offset_start 0u

static const uint16_t grabber_program_instructions[] = {
    0xa0c3, //  0: mov    isr, null                  
    0x2022, //  1: wait   0 pin, 2                   
            //     .wrap_target
    0x2023, //  2: wait   0 pin, 3                   
    0x00c0, //  3: jmp    pin, 0                     
    0x20a3, //  4: wait   1 pin, 3                   
    0x4002, //  5: in     pins, 2                    
    0x2023, //  6: wait   0 pin, 3                   
    0x20a3, //  7: wait   1 pin, 3                   
    0x4001, //  8: in     pins, 1                    
    0x2023, //  9: wait   0 pin, 3                   
    0x00c0, // 10: jmp    pin, 0                     
    0x20a3, // 11: wait   1 pin, 3                   
    0x4001, // 12: in     pins, 1                    
    0x2023, // 13: wait   0 pin, 3                   
    0x20a3, // 14: wait   1 pin, 3                   
    0x4001, // 15: in     pins, 1                    
    0x2023, // 16: wait   0 pin, 3                   
    0x00c0, // 17: jmp    pin, 0                     
    0x20a3, // 18: wait   1 pin, 3                   
    0x4001, // 19: in     pins, 1                    
    0x2023, // 20: wait   0 pin, 3                   
    0x20a3, // 21: wait   1 pin, 3                   
    0x4001, // 22: in     pins, 1                    
    0x2023, // 23: wait   0 pin, 3                   
    0x00c0, // 24: jmp    pin, 0                     
    0x20a3, // 25: wait   1 pin, 3                   
    0x4001, // 26: in     pins, 1                    
    0x2023, // 27: wait   0 pin, 3                   
    0x20a3, // 28: wait   1 pin, 3                   
    0x4001, // 29: in     pins, 1                    
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program grabber_program = {
    .instructions = grabber_program_instructions,
    .length = 30,
    .origin = -1,
};

static inline pio_sm_config grabber_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + grabber_wrap_target, offset + grabber_wrap);
    return c;
}
#endif

