
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += snd/fanfare.cpp
SRC += snd/mapple.cpp
SRC += snd/beep.cpp
SRC += snd/beep2.cpp
SRC += img/computer.cpp
SRC += img/frame.cpp
SRC += img/open.cpp
SRC += img/select.cpp
SRC += img/tiles.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
