
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/SpriteBank.cpp
SRC += src/Chamber10.cpp
SRC += src/Chamber9.cpp
SRC += src/Chamber8.cpp
SRC += src/Chamber7.cpp
SRC += src/Chamber6.cpp
SRC += src/Chamber5.cpp
SRC += src/Chamber4.cpp
SRC += src/Chamber3.cpp
SRC += src/Chamber2.cpp
SRC += src/Chamber1.cpp
SRC += src/Chamber0.cpp
SRC += src/PICOKIT.cpp
SRC += src/engineOBJ.cpp
SRC += src/main.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
