
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += ../FRUITY5/src/main.cpp

SRC += ../FRUITY5/img/logo.cpp

SRC += ../FRUITY5/snd/089.cpp
SRC += ../FRUITY5/snd/090.cpp
SRC += ../FRUITY5/snd/091.cpp
SRC += ../FRUITY5/snd/092.cpp
SRC += ../FRUITY5/snd/093.cpp
SRC += ../FRUITY5/snd/094.cpp
SRC += ../FRUITY5/snd/095.cpp
SRC += ../FRUITY5/snd/096.cpp
SRC += ../FRUITY5/snd/097.cpp
SRC += ../FRUITY5/snd/098.cpp
SRC += ../FRUITY5/snd/099.cpp
SRC += ../FRUITY5/snd/100.cpp
SRC += ../FRUITY5/snd/101.cpp
SRC += ../FRUITY5/snd/102.cpp
SRC += ../FRUITY5/snd/103.cpp
SRC += ../FRUITY5/snd/104.cpp
SRC += ../FRUITY5/snd/105.cpp
SRC += ../FRUITY5/snd/106.cpp
SRC += ../FRUITY5/snd/107.cpp
SRC += ../FRUITY5/snd/108.cpp
SRC += ../FRUITY5/snd/109.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
