
# PicoDVI library
ASRC += ../_libdvi/tmds_encode_asm.S
ASRC += ../_libsprite/sprite_asm.S
ASRC += ../_libsprite/tile_asm.S

CSRC += ../_libdvi/dvi_lib.c
CSRC += ../_libdvi/dvi_serialiser.c
CSRC += ../_libdvi/dvi_timing.c
CSRC += ../_libdvi/tmds_encode.c
CSRC += ../_libsprite/sprite.c
CSRC += ../_libsprite/tile.c

# ASM source files
ASRC +=

# C source files
CSRC += src/main.c
CSRC += src/dht.c

# C++ source files
SRC +=

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
