
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/logo.cpp

SRC += snd/089.cpp
SRC += snd/090.cpp
SRC += snd/091.cpp
SRC += snd/092.cpp
SRC += snd/093.cpp
SRC += snd/094.cpp
SRC += snd/095.cpp
SRC += snd/096.cpp
SRC += snd/097.cpp
SRC += snd/098.cpp
SRC += snd/099.cpp
SRC += snd/100.cpp
SRC += snd/101.cpp
SRC += snd/102.cpp
SRC += snd/103.cpp
SRC += snd/104.cpp
SRC += snd/105.cpp
SRC += snd/106.cpp
SRC += snd/107.cpp
SRC += snd/108.cpp
SRC += snd/109.cpp

# Makefile includes
include ../../../Makefile.inc
