
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/back.cpp
SRC += img/bird.cpp
SRC += img/cat.cpp
SRC += img/comet.cpp
SRC += img/digit.cpp
SRC += img/dog.cpp
SRC += img/frame.cpp
SRC += img/hare.cpp
SRC += img/mole.cpp
SRC += img/moon.cpp
SRC += img/mouse.cpp
SRC += img/pf.cpp
SRC += img/pfall.cpp
SRC += img/spark.cpp
SRC += img/star.cpp

SRC += snd/silent_night.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
