
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/colsel.cpp
SRC += img/colsel2.cpp
SRC += img/colsel3.cpp
SRC += img/curarrow.cpp
SRC += img/curbox.cpp
SRC += img/curbrush.cpp
SRC += img/curbucket.cpp
SRC += img/curcircle.cpp
#SRC += img/curcross.cpp
SRC += img/curdrop.cpp
SRC += img/curline.cpp
SRC += img/curline2.cpp
SRC += img/curpencil.cpp
SRC += img/currect.cpp
SRC += img/currect2.cpp
SRC += img/curring.cpp
SRC += img/curround.cpp
SRC += img/palette.cpp
SRC += img/tools.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
