
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/logo.cpp

SRC += snd/031.cpp
SRC += snd/032.cpp
SRC += snd/033.cpp
SRC += snd/034.cpp
SRC += snd/035.cpp
SRC += snd/036.cpp
SRC += snd/037.cpp
SRC += snd/038.cpp
SRC += snd/039.cpp
SRC += snd/040.cpp
SRC += snd/041.cpp
SRC += snd/042.cpp
SRC += snd/043.cpp
SRC += snd/044.cpp
SRC += snd/045.cpp
SRC += snd/046.cpp
SRC += snd/047.cpp
SRC += snd/048.cpp
SRC += snd/049.cpp
SRC += snd/050.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
