
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp
SRC += img/repro1.cpp
SRC += img/repro2.cpp
SRC += img/repro3.cpp
SRC += snd/test.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
