
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += ../FRUITY4/src/main.cpp

SRC += ../FRUITY4/img/logo.cpp

SRC += ../FRUITY4/snd/071.cpp
SRC += ../FRUITY4/snd/072.cpp
SRC += ../FRUITY4/snd/073.cpp
SRC += ../FRUITY4/snd/074.cpp
SRC += ../FRUITY4/snd/075.cpp
SRC += ../FRUITY4/snd/076.cpp
SRC += ../FRUITY4/snd/077.cpp
SRC += ../FRUITY4/snd/078.cpp
SRC += ../FRUITY4/snd/079.cpp
SRC += ../FRUITY4/snd/080.cpp
SRC += ../FRUITY4/snd/081.cpp
SRC += ../FRUITY4/snd/082.cpp
SRC += ../FRUITY4/snd/083.cpp
SRC += ../FRUITY4/snd/084.cpp
SRC += ../FRUITY4/snd/085.cpp
SRC += ../FRUITY4/snd/086.cpp
SRC += ../FRUITY4/snd/087.cpp
SRC += ../FRUITY4/snd/088.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
