
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += img/logo.cpp

SRC += snd/110.cpp
SRC += snd/111.cpp
SRC += snd/112.cpp
SRC += snd/113.cpp
SRC += snd/114.cpp
SRC += snd/115.cpp
SRC += snd/116.cpp
SRC += snd/117.cpp
SRC += snd/118.cpp
SRC += snd/119.cpp
SRC += snd/120.cpp
SRC += snd/121.cpp
SRC += snd/122.cpp
SRC += snd/123.cpp
SRC += snd/124.cpp
SRC += snd/125.cpp
SRC += snd/126.cpp
SRC += snd/127.cpp
SRC += snd/128.cpp
SRC += snd/129.cpp
SRC += snd/130.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
