
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/infones/InfoNES.cpp
SRC += src/infones/InfoNES_Mapper.cpp
SRC += src/infones/NES_APU.cpp
SRC += src/infones/K6502.cpp
SRC += src/infones/K6502_rw.cpp

SRC += src/main.cpp
SRC += src/emu_nes_msg.cpp
SRC += src/emu_nes_menu.cpp
SRC += src/program.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
