
# ASM source files
ASRC +=

# C source files
CSRC += font/font_141pf_8x16.c
CSRC += font/font_141pf_8x14.c
CSRC += font/font_141pf_8x13.c
CSRC += font/font_141pf_8x12.c

# C++ source files
SRC += src/main.cpp

SRC += img/keybup.cpp
SRC += img/keybdn.cpp
SRC += img/lightoff.cpp
SRC += img/lighton.cpp
SRC += img/logo1.cpp
SRC += img/logo2.cpp

SRC += firmware/busicom.cpp

SRC += snd/print.cpp
SRC += snd/idle.cpp
SRC += snd/click.cpp

# Makefile includes
include ../../../Makefile.inc
