
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/main.cpp

SRC += src/actor.cpp
SRC += src/background.cpp
SRC += src/bonus.cpp
SRC += src/bullet.cpp
SRC += src/disp.cpp
SRC += src/enemy.cpp
SRC += src/foot.cpp
SRC += src/game.cpp
SRC += src/gameend.cpp
SRC += src/gamemenu.cpp
SRC += src/gamestart.cpp
SRC += src/header.cpp
SRC += src/missile.cpp
SRC += src/point.cpp
SRC += src/random.cpp
SRC += src/sound.cpp
SRC += src/titlescreen.cpp

# images
SRC += img/title.cpp

SRC += img/bullet1.cpp
SRC += img/bullet2.cpp
SRC += img/bullet3.cpp

SRC += img/explosion.cpp

SRC += img/shadow.cpp

SRC += img/blood.cpp

SRC += img/picopad.cpp
SRC += img/picopad1.cpp
SRC += img/picopad2.cpp
SRC += img/picopad3.cpp
SRC += img/picopad4.cpp
SRC += img/heart.cpp
SRC += img/bonuscloud.cpp

SRC += img/00jill.cpp
SRC += img/00shuriken.cpp

SRC += img/01meadow.cpp
SRC += img/01meadow2.cpp
SRC += img/01meadow3.cpp
SRC += img/01bird.cpp
SRC += img/01fly.cpp
SRC += img/01wasp.cpp
SRC += img/01hornet.cpp
SRC += img/01seed.cpp

SRC += img/02jungle.cpp
SRC += img/02jungle2.cpp
SRC += img/02jungle3.cpp
SRC += img/02parrot.cpp
SRC += img/02dragonfly.cpp
SRC += img/02moth.cpp
SRC += img/02kestrel.cpp
SRC += img/02berry.cpp

SRC += img/03sandbeach.cpp
SRC += img/03sandbeach2.cpp
SRC += img/03sandbeach3.cpp
SRC += img/03scarabeus.cpp
SRC += img/03maggot.cpp
SRC += img/03eagle.cpp
SRC += img/03antman.cpp
SRC += img/03sandball.cpp

SRC += img/04underwater.cpp
SRC += img/04underwater2.cpp
SRC += img/04underwater3.cpp
SRC += img/04stingray.cpp
SRC += img/04fish.cpp
SRC += img/04anglerfish.cpp
SRC += img/04shark.cpp
SRC += img/04flash.cpp

SRC += img/05iceland.cpp
SRC += img/05iceland2.cpp
SRC += img/05iceland3.cpp
SRC += img/05icebird.cpp
SRC += img/05penguin.cpp
SRC += img/05polarbear.cpp
SRC += img/05snowflake.cpp
SRC += img/05crystal.cpp

SRC += img/06fireland.cpp
SRC += img/06fireland2.cpp
SRC += img/06fireland3.cpp
SRC += img/06dragon.cpp
SRC += img/06phoenix.cpp
SRC += img/06fireball.cpp
SRC += img/06evil.cpp
SRC += img/06fire.cpp

SRC += img/07haunted.cpp
SRC += img/07haunted2.cpp
SRC += img/07haunted3.cpp
SRC += img/07ghost.cpp
SRC += img/07pumpkin.cpp
SRC += img/07zombie.cpp
SRC += img/07death.cpp
SRC += img/07scream.cpp

SRC += img/08spacecraft.cpp
SRC += img/08spacecraft2.cpp
SRC += img/08spacecraft3.cpp
SRC += img/08r2d2.cpp
SRC += img/08camera.cpp
SRC += img/08explorer.cpp
SRC += img/08dron.cpp
SRC += img/08laser.cpp

SRC += img/09galaxy.cpp
SRC += img/09galaxy2.cpp
SRC += img/09galaxy3.cpp
SRC += img/09ufo.cpp
SRC += img/09enterprise.cpp
SRC += img/09klingon.cpp
SRC += img/09deathstar.cpp
SRC += img/09phaser.cpp

SRC += img/10planet.cpp
SRC += img/10planet2.cpp
SRC += img/10planet3.cpp
SRC += img/10squirrel.cpp
SRC += img/10alien.cpp
SRC += img/10xenomorph.cpp
SRC += img/10meteor.cpp
SRC += img/10rocket.cpp

SRC += img/11candyland.cpp
SRC += img/11candyland2.cpp
SRC += img/11candyland3.cpp
SRC += img/11gingerbread.cpp
SRC += img/11candycane.cpp
SRC += img/11lollipop.cpp
SRC += img/11fatman.cpp
SRC += img/11sugarbomb.cpp

SRC += img/12surreal.cpp
SRC += img/12surreal2.cpp
SRC += img/12surreal3.cpp
SRC += img/12devil.cpp
SRC += img/12cloud.cpp
SRC += img/12star.cpp
SRC += img/12moon.cpp
SRC += img/12spiral.cpp

# sounds
SRC += snd/music1.cpp
SRC += snd/music2.cpp
SRC += snd/music3.cpp
SRC += snd/music4.cpp
SRC += snd/music5.cpp
SRC += snd/music6.cpp
SRC += snd/music7.cpp
SRC += snd/music8.cpp
SRC += snd/music9.cpp
SRC += snd/music10.cpp
SRC += snd/music11.cpp
SRC += snd/music12.cpp

SRC += snd/enemyhit.cpp
SRC += snd/swing.cpp
SRC += snd/minigun.cpp
SRC += snd/gun.cpp
SRC += snd/noise.cpp
SRC += snd/electricity.cpp
SRC += snd/glass.cpp
SRC += snd/flame.cpp
SRC += snd/screaming.cpp
SRC += snd/lasershot.cpp
SRC += snd/phasershot.cpp
SRC += snd/rocketshot.cpp
SRC += snd/throw.cpp
SRC += snd/blackhole.cpp
SRC += snd/blackhole2.cpp
SRC += snd/fail.cpp
SRC += snd/zing.cpp
SRC += snd/bigbonus.cpp

# Makefile includes
include ../../../Makefile.inc
