
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/enemy.cpp
SRC += src/fuel.cpp
SRC += src/gates.cpp
SRC += src/goals.cpp
SRC += src/ground.cpp
SRC += src/lives.cpp
SRC += src/main.cpp
SRC += src/open.cpp
SRC += src/score.cpp
SRC += src/ship.cpp
SRC += src/shot.cpp
SRC += src/stars.cpp

SRC += img/bomb.cpp
SRC += img/boss.cpp
SRC += img/city1.cpp
SRC += img/city2.cpp
SRC += img/digits.cpp
SRC += img/explosion.cpp
SRC += img/gateimg.cpp
SRC += img/goalimg.cpp
SRC += img/grass1.cpp
SRC += img/grass2.cpp
SRC += img/grass3.cpp
SRC += img/grass4.cpp
SRC += img/liveimg.cpp
SRC += img/shipimg.cpp
SRC += img/shotimg.cpp
SRC += img/skyline.cpp
SRC += img/title.cpp
SRC += img/ufo.cpp
SRC += img/ufo2.cpp

SRC += snd/entering.cpp
SRC += snd/explos.cpp
SRC += snd/fuelsnd.cpp
SRC += snd/gateok.cpp
SRC += snd/hit.cpp
SRC += snd/laser.cpp
SRC += snd/livessnd.cpp

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
