
# ASM source files
ASRC +=

# C source files
CSRC +=

# C++ source files
SRC += src/table.cpp
SRC += src/main.cpp
SRC += src/minigb_apu.c
SRC += src/peanut_gb_exec.c
SRC += src/peanut_gb_line.c
SRC += src/peanut_gb_mem.c
SRC += src/peanut_gb.c
SRC += src/program.cpp
SRC += src/emu_gb_menu.c
SRC += src/emu_gb_msg.c

# Path to root directory from the project directory (without trailing '/' delimiter)
PICO_ROOT_PATH = ../../..

# Makefile includes
include ${PICO_ROOT_PATH}/Makefile.inc
